package com.pomodorokombat.app;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.ToneGenerator;import android.media.AudioManager;import android.view.*;import java.util.*;

public class MainActivity extends Activity{
    KombatView v; CountDownTimer timer; long left=25*60000L; int mode=25; boolean running=false; int xp=250,wins=0,rounds=0,streak=0; String screen="welcome", lang="RU", theme="SCORPION"; ToneGenerator tone;
    public void onCreate(Bundle b){super.onCreate(b); tone=new ToneGenerator(AudioManager.STREAM_MUSIC,90); v=new KombatView(this); setContentView(v); if(Build.VERSION.SDK_INT>=33) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},1); createChannel();}
    void start(){ if(running)return; running=true; beep(1); timer=new CountDownTimer(left,1000){public void onTick(long m){left=m;v.invalidate();} public void onFinish(){running=false;left=mode*60000L;wins++;rounds++;xp+=100;streak=Math.min(7,streak+1);beep(2);vibrate();notifyDone();v.invalidate();}}.start();}
    void pause(){running=false;if(timer!=null)timer.cancel();v.invalidate();}
    void setMode(int m){pause();mode=m;left=m*60000L;screen="timer";v.invalidate();}
    void beep(int type){ if(tone!=null) tone.startTone(type==1?ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD:ToneGenerator.TONE_CDMA_ABBR_ALERT,220); }
    void vibrate(){((android.os.Vibrator)getSystemService(VIBRATOR_SERVICE)).vibrate(android.os.VibrationEffect.createOneShot(400,180));}
    void createChannel(){ if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("kombat","Pomodoro Kombat",NotificationManager.IMPORTANCE_DEFAULT);getSystemService(NotificationManager.class).createNotificationChannel(c);} }
    void notifyDone(){ Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"kombat"):new Notification.Builder(this); b.setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle("Pomodoro Kombat").setContentText(lang.equals("RU")?"Раунд завершён. Победа!":"Round complete. Victory!").setAutoCancel(true); ((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(7,b.build()); }
    class KombatView extends View{Paint p=new Paint(1); RectF r=new RectF(); KombatView(Context c){super(c);p.setTypeface(Typeface.create(Typeface.MONOSPACE,Typeface.BOLD));}
        protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(5,5,5));c.drawRect(0,0,w,h,p);drawBg(c,w,h); if(screen.equals("welcome"))welcome(c,w,h); else if(screen.equals("timer"))timer(c,w,h); else if(screen.equals("missions"))missions(c,w,h); else stats(c,w,h); nav(c,w,h);} 
        void drawBg(Canvas c,int w,int h){p.setColor(theme.equals("SCORPION")?Color.rgb(90,15,0):Color.rgb(0,35,70)); for(int i=0;i<40;i++) c.drawCircle((i*73)%w,(i*137)%h,2+(i%5),p);}
        void txt(Canvas c,String s,float x,float y,int sz,int col){p.setColor(col);p.setTextSize(sz);p.setTextAlign(Paint.Align.CENTER);c.drawText(s,x,y,p);} void box(Canvas c,float l,float t,float rr,float b,int col){p.setColor(Color.rgb(28,25,22));r.set(l,t,rr,b);c.drawRoundRect(r,14,14,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(col);c.drawRoundRect(r,14,14,p);p.setStyle(Paint.Style.FILL);} 
        void welcome(Canvas c,int w,int h){txt(c,"🐉",w/2,160,72,Color.YELLOW);txt(c,"POMODORO",w/2,260,52,0xffffcc33);txt(c,"KOMBAT",w/2,320,48,0xffd90000);txt(c,"PREPARE YOURSELF",w/2,430,30,0xffd90000);txt(c,"FOCUS. FIGHT. FINISH.",w/2,490,25,0xffeeeeee);box(c,w*.25f,h-260,w*.75f,h-190,0xffffaa00);txt(c,"ENTER",w/2,h-213,32,0xffffcc33);txt(c,"18+ FOR WARRIORS ONLY",w/2,h-110,22,0xffcc2222);} 
        void timer(Canvas c,int w,int h){txt(c,"WARRIOR        WINS: "+wins,w/2,70,24,0xffffcc33);txt(c,lang.equals("RU")?"ФОКУС РАУНД":"FOCUS SESSION",w/2,160,31,0xffdd1111);p.setColor(0xff171717);c.drawCircle(w/2,h/2-90,185,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(12);p.setColor(0xff5b4a2c);c.drawCircle(w/2,h/2-90,185,p);p.setStyle(Paint.Style.FILL);long sec=left/1000;txt(c,String.format(Locale.US,"%02d:%02d",sec/60,sec%60),w/2,h/2-70,62,0xffe00000);txt(c,"ROUND "+(rounds+1),w/2,h/2,28,0xffffcc33);box(c,w*.22f,h-260,w*.78f,h-180,0xffffaa00);txt(c,running?"PAUSE":"FIGHT!",w/2,h-210,34,0xffd90000);} 
        void missions(Canvas c,int w,int h){txt(c,"SESSIONS",w/2,80,36,0xffffcc33);int[] ms={25,15,50,5};String[] names={"FOCUS SESSION","SHORT SESSION","LONG SESSION","CUSTOM SESSION"};for(int i=0;i<4;i++){box(c,40,140+i*150,w-40,260+i*150,i==0?0xffd90000:0xff996633);txt(c,names[i],w/2,185+i*150,26,0xffffcc33);txt(c,(i==3?"5-90":ms[i])+" MIN",w/2,225+i*150,22,0xffeeeeee);}}
        void stats(Canvas c,int w,int h){txt(c,"STATS",w/2,80,38,0xffffcc33);box(c,50,130,w-50,310,0xff996633);txt(c,"WARRIOR",w/2,185,30,0xffffcc33);txt(c,"NOVICE  "+xp+" / 1000 XP",w/2,235,24,0xffeeeeee);box(c,50,360,w-50,620,0xff996633);txt(c,"SESSIONS: "+rounds,w/2,420,26,0xffeeeeee);txt(c,"WINS: "+wins,w/2,470,26,0xffeeeeee);txt(c,"STREAK: "+streak+" DAYS",w/2,520,26,0xffeeeeee);txt(c,"LANG: "+lang+"  THEME: "+theme,w/2,570,21,0xffffcc33);} 
        void nav(Canvas c,int w,int h){int y=h-85;String[] a={"TIMER","STATS","MISSIONS","SETTINGS"};for(int i=0;i<4;i++){txt(c,a[i],w*(i+.5f)/4,y,20,0xffffcc33);}}
        public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();int w=getWidth(),h=getHeight(); if(screen.equals("welcome")){screen="timer";invalidate();return true;} if(y>h-150){int i=(int)(x/(w/4f)); if(i==0)screen="timer"; if(i==1)screen="stats"; if(i==2)screen="missions"; if(i==3){lang=lang.equals("RU")?"EN":"RU";theme=theme.equals("SCORPION")?"SUBZERO":"SCORPION";} invalidate();return true;} if(screen.equals("timer")&&y>h-300){if(running)pause();else start();return true;} if(screen.equals("missions")){int idx=(int)((y-140)/150); if(idx>=0&&idx<4)setMode(idx==0?25:idx==1?15:idx==2?50:30);} return true;}
    }
}
